services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: easy-chat-etcd
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-node1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - easy-chat-net
  
  redis:
    image: redis:5.0.7
    container_name: easy-chat-redis
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/redis/data:/data
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - easy-chat-net
  mysql:
    image: mysql:5.7
    container_name: easy-chat-mysql
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=111
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/mysql/data:/var/lib/mysql
      - ./deploy/mysql/log:/var/log/mysql
      - ./deploy/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - easy-chat-net

networks:
  easy-chat-net:
    driver: bridge
# docker run --name redis507 -p 6379:6379 -d redis:5.0.7
# docker run -it --network host --rm redis:5.0.7 redis-cli